Repository DeutscheModelUnitedNations/munify-delegator, pull requests merged in 2024-12, with the labels that each got.

#148 ✨ feature: Add manual conference state
  bun.lockb
  prisma/dev.seed.ts
  prisma/migrations/20241127144551_/migration.sql
  prisma/schema.prisma
  prisma/seed_conference/mun_sh_2025.ts
  prisma/seed_conference/munbw_2025.ts
  schema.graphql
  src/api/resolvers/modules/conference/conference.ts
  src/i18n/de.json
  src/lib/components/ConferenceCard/ConferenceCard.svelte
  src/routes/(authenticated)/dashboard/+layout.gql
  src/routes/(authenticated)/dashboard/+page.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.gql
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/configuration/+page.server.ts
  src/routes/(authenticated)/management/[conferenceId]/configuration/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/configuration/form-schema.ts
  src/routes/(authenticated)/registration/+page.gql
  src/routes/+page.gql
  src/routes/+page.svelte
  src/tasks/conferenceStatus.ts
Labels: feature

#157 ✨ feature: adds otel support for logs
  .env.example
  bun.lockb
  dev.docker-compose.yml
  package.json
  prisma/schema.prisma
  src/api/resolvers/api.ts
  src/api/resolvers/builder.ts
  src/api/resolvers/tracer.ts
  src/config/private.ts
Labels: feature

#159 ⬆️ improvement: Better supervisor dashboard
  src/api/abilities/entities/conferenceSupervisor.ts
  src/api/resolvers/builder.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.gql
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/Supervisor.svelte
Labels: enhancement

#160 Features: Preparation-Link, Better Info Board with Markdown
  bun.lockb
  package.json
  prisma/migrations/20241219134106_add_link_to_preparation_guide_to_conference_entity/migration.sql
  prisma/schema.prisma
  schema.graphql
  src/api/resolvers/builder.ts
  src/api/resolvers/modules/conference/conference.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/Form/FormTextArea.svelte
  src/lib/components/Markdown/Markdown.svelte
  src/lib/components/TasksAlert/TaskAlertCard.svelte
  src/lib/components/TasksAlert/TasksWrapper.svelte
  src/routes/(authenticated)/Breadcrumbs.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.gql
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/info/+page.gql
  src/routes/(authenticated)/dashboard/[conferenceId]/info/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationPreparationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/SingleParticipantPreparationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/Supervisor.svelte
  src/routes/(authenticated)/management/[conferenceId]/configuration/+page.server.ts
  src/routes/(authenticated)/management/[conferenceId]/configuration/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/configuration/form-schema.ts
Labels: feature

#161 ✨ feature: Seats Overview
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/DataTable/DataTable.svelte
  src/lib/components/NavMenu/NavMenuButton.svelte
  src/routes/(authenticated)/Breadcrumbs.svelte
  src/routes/(authenticated)/management/[conferenceId]/+layout.svelte
  src/routes/(authenticated)/management/[conferenceId]/delegations/DelegationDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/participants/UserDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/+page.gql
  src/routes/(authenticated)/management/[conferenceId]/seats/+page.svelte
  src/routes/Footer.svelte
Labels: feature

#164 🐞 fix: update condition for displaying Supervisor component in dashboard
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.svelte
Labels: bug
