Repository DeutscheModelUnitedNations/munify-delegator, pull requests merged in 2024-10, with the labels that each got.

#109 🐞 fix: prevent failure & add error messages on failed refresh attempts
  src/api/auth/abilities/abilities.ts
  src/api/auth/abilities/entities/committee.ts
  src/api/auth/abilities/entities/conference.ts
  src/api/auth/abilities/entities/conferenceParticipantStatus.ts
  src/api/auth/abilities/entities/conferenceSupervisor.ts
  src/api/auth/abilities/entities/customConferenceRole.ts
  src/api/auth/abilities/entities/delegation.ts
  src/api/auth/abilities/entities/delegationMember.ts
  src/api/auth/abilities/entities/nation.ts
  src/api/auth/abilities/entities/nonStateActor.ts
  src/api/auth/abilities/entities/roleApplication.ts
  src/api/auth/abilities/entities/singleParticipant.ts
  src/api/auth/abilities/entities/teamMember.ts
  src/api/auth/abilities/entities/user.ts
  src/api/auth/oidc.ts
  src/api/auth/oidcFlow.ts
  src/api/auth/oidcPlugin.ts
  src/api/auth/permissionsPlugin.ts
  src/api/client.ts
  src/api/routes/auth.ts
  src/api/routes/committee.ts
  src/api/routes/conference.ts
  src/api/routes/conferenceSupervisor.ts
  src/api/routes/customConferenceRole.ts
  src/api/routes/delegation.ts
  src/api/routes/delegationMember.ts
  src/api/routes/nonStateActor.ts
  src/api/routes/roleApplication.ts
  src/api/routes/singleParticipant.ts
  src/api/routes/user.ts
  src/api/util/crudmaker.ts
  src/api/util/logger.ts
  src/config/private.ts
  src/i18n/de.json
  src/lib/components/AssistentModal/Choice.svelte
  src/routes/(authenticated)/+layout.server.ts
  src/routes/(authenticated)/+layout.svelte
  src/routes/(authenticated)/my-account/+page.svelte
  src/routes/auth/login-callback/+page.server.ts
  src/routes/auth/logout-callback/+page.server.ts
Labels: bug

#106 🐞 fix: Fix gender stars in mermaid graph
  src/routes/(authenticated)/registration/[conference]/+page.svelte
Labels: bug

#111 🚀 enhancement: Enable Image Optimization
  bun.lockb
  package.json
  src/lib/components/Footer.svelte
  src/routes/+page.svelte
  vite.config.ts
Labels: enhancement

#115 ✨ feature: Display Active Registration Periods on home page
  src/routes/+page.svelte
  src/routes/+page.ts
Labels: feature

#116 🐞 fix: minor fixes in permissions and other bugs for admin panel
  src/api/auth/abilities/entities/delegation.ts
  src/api/auth/abilities/entities/singleParticipant.ts
  src/api/routes/conferenceSupervisor.ts
  src/api/routes/delegation.ts
  src/api/routes/singleParticipant.ts
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/management/[conferenceId]/configuration/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/configuration/FileInput.svelte
  src/routes/(authenticated)/management/[conferenceId]/participants/UserDrawer.svelte
Labels: bug

#93 🐞 fix: use correct adjustments in case of role applicaiton deletion
  src/api/routes/roleApplication.ts
Labels: bug

#117 ⬆️ improvement: Better Slack Notification with comparison
  .gitignore
  prisma/db.ts
  src/api/functions/stats.ts
  src/api/routes/conference.ts
  src/tasks/conferenceStatus.ts
Labels: enhancement

#128 🐞 fix: remove the unwanted cookie logs
  bun.lockb
  package.json
  src/api/auth/oidcPlugin.ts
Labels: bug

#129 🚀 enhancement: re fetch user data from issuer when visiting the profile page
  src/api/auth/oidcFlow.ts
  src/api/routes/auth.ts
  src/api/routes/user.ts
  src/i18n/de.json
  src/routes/(authenticated)/my-account/+page.svelte
  src/routes/(authenticated)/my-account/+page.ts
Labels: enhancement

#130 🚀 enhancement: Show toast in case of incomplete profile data
  src/api/routes/conference.ts
  src/api/routes/delegation.ts
  src/api/routes/user.ts
  src/api/services/stats.ts
  src/api/services/userDataComplete.ts
  src/i18n/de.json
  src/routes/(authenticated)/+layout.svelte
  src/routes/(authenticated)/my-account/+page.svelte
  src/tasks/conferenceStatus.ts
Labels: enhancement

#133 🚀 enhancement: add deletion cascades
  prisma/migrations/20241011115355_/migration.sql
  prisma/schema.prisma
Labels: enhancement

#138 🐞 fix: Fix ownership in docker compose file to allow tasks to write
  Dockerfile
  src/api/util/logger.ts
Labels: bug
