Repository DeutscheModelUnitedNations/munify-delegator, pull requests merged in 2024-09, with the labels that each got.

#23 ⬆️ improvement (App Frontend): Pronouns are now prefilled when binary genders are selected
  src/api/routes/roleApplication.ts
  src/api/routes/user.ts
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/dashboard/+page.ts
  src/routes/(authenticated)/my-account/+page.svelte
Labels: enhancement

#24 🐞 fix (App Frontend): Delegation Deletion Button
  src/routes/(authenticated)/dashboard/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/DelegationRegistrationStage.svelte
Labels: bug

#25 🐞 fix (App Frontend): Phone Regex on /my-account
  src/api/routes/user.ts
  src/routes/(authenticated)/my-account/+page.svelte
Labels: bug

#26 ✨ feat (App Frontend): Make Delegation Code rotatable by Head Delegate
  src/api/routes/delegation.ts
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/dashboard/[conferenceId]/DelegationRegistrationStage.svelte
Labels: enhancement

#27 ✨ feat (App Frontend): No-Conference-Open-for-Registration Placeholder
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/registration/+page.svelte
Labels: enhancement

#38 🐞 fix: Allows cascading deletes for delegation applications
  prisma/migrations/20240917124921_/migration.sql
  prisma/schema.prisma
Labels: bug

#41 ✨ feature: add user feedback (toasts) for occurring errors and failed calls
  bun.lockb
  package.json
  src/api/client.ts
  src/app.css
  src/lib/components/ErrorToast.svelte
  src/routes/+layout.svelte
Labels: enhancement

#45 ✨ feat (App Frontend): Better Supervisor Accordion
  .prettierignore
  src/routes/(authenticated)/dashboard/[conferenceId]/Supervisor.svelte
Labels: bug

#43 ✨ feat (App Frontend): Add Favicon and Title
  src/i18n/de.json
  src/lib/components/Footer.svelte
  src/routes/(authenticated)/dashboard/+layout.svelte
  src/routes/(authenticated)/management/layout.svelte
  src/routes/(authenticated)/my-account/+page.svelte
  src/routes/(authenticated)/registration/+layout.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/browserconfig.xml
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/favicon.png
  static/mstile-150x150.png
  static/safari-pinned-tab.svg
  static/site.webmanifest
Labels: enhancement

#46 ✨ feat (App Frontend): Loading Spinners for Buttons
  src/i18n/de.json
  src/lib/components/SquareButtonWithLoadingState.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/DelegationRegistrationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/SelectDelegationPreferencesModal.svelte
Labels: enhancement

#39 ✨ feature: allows the user to see their own system roles in the profiles page
  src/api/auth/oidc.ts
  src/api/routes/auth.ts
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/my-account/+page.svelte
  src/routes/(authenticated)/my-account/+page.ts
Labels: enhancement

#53 🐞 fix: add i18n to delegation error messages
  bun.lockb
  package.json
  src/api/routes/delegation.ts
  src/api/util/fetchUserParticipations.ts
  src/api/util/languageExtractor.ts
  src/i18n/de.json
  src/i18n/en.json
Labels: bug

#70 🐞 fix: Restrict changes to single applications to non applied entities
  src/api/auth/abilities/entities/singleParticipant.ts
  src/api/routes/singleParticipant.ts
Labels: bug

#72 🚀 enhancement: Add a disclaimer for account update flow
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/my-account/+page.svelte
Labels: enhancement

#57 🐞 fix (App Frontend): Make questionair optional
  prisma/migrations/20240919203441_/migration.sql
  prisma/schema.prisma
  src/api/routes/delegation.ts
  src/app.css
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/registration/[conference]/create/+page.svelte
Labels: bug

#60 🐞 fix: Remove german translations from en.json
  .prettierignore
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/AssistentModal/Flow/SupervisorUsersAlreadyRegistered.svelte
Labels: bug

#73 🐞 fix (App Frontend): Make changes to information and motivation changable
  src/routes/(authenticated)/dashboard/[conferenceId]/SingleParticipantRegistrationStage.svelte
Labels: bug

#79 ⬆️ improvement (App Frontend): Updated Seed
  prisma/seed_conference/countries_mun-sh_2025.json
  prisma/seed_conference/mun_sh_2025.ts
Labels: enhancement

#98 ✨ feat (App Frontend): Access Control for Admin Pages
  dev.docker-compose.yml
  src/assets/undraw/500.svg
  src/assets/undraw/access_denied.svg
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/ManagementSidebarWrapper.svelte
  src/routes/(authenticated)/management/+layout.svelte
  src/routes/(authenticated)/management/+layout.ts
  src/routes/(authenticated)/management/+page.svelte
  src/routes/(authenticated)/management/+page.ts
  src/routes/(authenticated)/management/[conferenceId]/+layout.ts
  src/routes/(authenticated)/management/[conferenceId]/stats/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/+page.ts
  src/routes/+error.svelte
Labels: feature

#103 ✨ feature: Cronjob Tasks
  .gitignore
  Dockerfile
  bun.lockb
  dev.docker-compose.yml
  example/docker-compose.yml
  package.json
  src/config/private.ts
  src/config/public.ts
  src/config/schemaMapper.ts
  src/tasks/conferenceStatus.ts
  src/tasks/config.ts
  src/tasks/index.ts
  src/tasks/tasksDb.ts
  tasksBuild.ts
Labels: feature
