Repository DeutscheModelUnitedNations/munify-delegator, pull requests merged in 2025-09, with the labels that each got.

#254 🚀 enhancement: set limits for the form inputs
  .env.example
  messages/de.json
  src/api/resolvers/modules/delegation.ts
  src/api/resolvers/modules/singleParticipant.ts
  src/config/public.ts
  src/lib/components/Form/FormTextArea.svelte
  src/lib/components/Form/FormTextInput.svelte
  src/lib/schemata/applicationForm.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/+layout.server.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.server.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationRegistrationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/SingleParticipantRegistrationStage.svelte
  src/routes/(authenticated)/registration/[conferenceId]/create-delegation/+page.server.ts
  src/routes/(authenticated)/registration/[conferenceId]/create-delegation/+page.svelte
  src/routes/(authenticated)/registration/[conferenceId]/create-delegation/form-schema.ts
  src/routes/(authenticated)/registration/[conferenceId]/individual/[roleId]/+page.server.ts
  src/routes/(authenticated)/registration/[conferenceId]/individual/[roleId]/+page.svelte
  src/routes/(authenticated)/registration/[conferenceId]/individual/[roleId]/form-schema.ts
Labels: enhancement

#258 ✨ feat: Add new Seats overview
  messages/de.json
  messages/en.json
  prisma/seed/real/sh26.json
  src/api/resolvers/modules/nation.ts
  src/lib/components/ConferenceCard/ConferenceCard.svelte
  src/lib/components/Flag.svelte
  src/lib/components/NSAPool.svelte
  src/lib/components/NationPool.svelte
  src/lib/components/NationsWithCommitteesTable.svelte
  src/lib/components/PoolSorting.svelte
  src/lib/queries/myConferenceparticipationQuery.ts
  src/lib/services/getUniqueNations.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationRegistrationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/SelectDelegationPreferencesModal.svelte
  src/routes/seats/[conferenceId]/+page.gql
  src/routes/seats/[conferenceId]/+page.svelte
Labels: feature

#259 🐞 fix: Correct head delegate condition in delegation application button
  .trivyignore
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationRegistrationStage.svelte
Labels: bug
