Repository DeutscheModelUnitedNations/munify-delegator, pull requests merged in 2025-02, with the labels that each got.

#194 🚀 enhancement: make user mail unique
  prisma/migrations/20250207121507_/migration.sql
  prisma/schema.prisma
Labels: enhancement

#196 ✨ feature: Add unique constraints and timestamps to all models
  dev-restart-database.sh
  prisma/migrations/20250207125305_add_unique_constraints_for_delegation_role_assignemnts/migration.sql
  prisma/migrations/20250207125510_add_timestamps_for_conference/migration.sql
  prisma/migrations/20250207125544_add_timestamps_for_committee/migration.sql
  prisma/migrations/20250207125814_add_timestamps_for_all_remaining_models/migration.sql
  prisma/schema.prisma
  schema.graphql
  src/api/resolvers/modules/conferenceSupervisor.ts
  src/api/resolvers/modules/delegation.ts
  src/api/resolvers/modules/delegationMember.ts
  src/lib/components/DelegationStats/RoleWidget.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/SelectDelegationPreferencesModal.svelte
  src/routes/(authenticated)/registration/[conferenceId]/join-delegation-supervisor/+page.svelte
  src/routes/(authenticated)/registration/[conferenceId]/join-delegation/+page.svelte
Labels: feature

#199 ✨ feature: Add better seeding scripts for development
  CONTRIBUTING.md
  bun.lockb
  package.json
  prisma/db.ts
  prisma/defaultData/createDefaultData.ts
  prisma/defaultData/nations.ts
  prisma/dev.seed.ts
  prisma/migrations/20250105093928_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/pothos.config.cjs
  prisma/schema.prisma
  prisma/seed.ts
  prisma/seed/dev/committee.ts
  prisma/seed/dev/conference.ts
  prisma/seed/dev/conferenceSupervisor.ts
  prisma/seed/dev/customConferenceRole.ts
  prisma/seed/dev/delegation.ts
  prisma/seed/dev/delegationMember.ts
  prisma/seed/dev/nonStateActor.ts
  prisma/seed/dev/paymentTransaction.ts
  prisma/seed/dev/seed.ts
  prisma/seed/dev/singleParticipant.ts
  prisma/seed/dev/teamMember.ts
  prisma/seed/dev/user.ts
  prisma/seed/real/countries_mun-sh_2025.json
  prisma/seed/real/countries_munbw_2025.json
  prisma/seed/real/mun_sh_2025.ts
  prisma/seed/real/munbw_2025.ts
  prisma/seed/real/nsa_munbw_2025.json
  prisma/seed/real/stats.ts
  schema.graphql
  scripts/add_new_translation.ts
  src/i18n/de.json
  src/lib/components/Breadcrumbs.svelte
  src/routes/(authenticated)/Breadcrumbs.svelte
Labels: feature

#200 ✨ feature: add downloads section and table-downloads for badge generation
  bun.lockb
  dev-restart-database.sh
  package.json
  prisma/defaultData/createDefaultData.ts
  prisma/seed/dev/committee.ts
  prisma/seed/dev/conference.ts
  prisma/seed/dev/conferenceSupervisor.ts
  prisma/seed/dev/customConferenceRole.ts
  prisma/seed/dev/delegation.ts
  prisma/seed/dev/delegationMember.ts
  prisma/seed/dev/nonStateActor.ts
  prisma/seed/dev/paymentTransaction.ts
  prisma/seed/dev/seed.ts
  prisma/seed/dev/singleParticipant.ts
  prisma/seed/dev/teamMember.ts
  prisma/seed/dev/user.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/DataTable/DataTable.svelte
  src/lib/services/formatNames.ts
  src/routes/(authenticated)/Breadcrumbs.svelte
  src/routes/(authenticated)/management/[conferenceId]/+layout.svelte
  src/routes/(authenticated)/management/[conferenceId]/downloads/+layout.svelte
  src/routes/(authenticated)/management/[conferenceId]/downloads/+page.gql
  src/routes/(authenticated)/management/[conferenceId]/downloads/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/downloads/BadgeData.svelte
  src/routes/(authenticated)/management/[conferenceId]/downloads/DownloadElement.svelte
  src/routes/(authenticated)/management/[conferenceId]/downloads/DownloadSection.svelte
Labels: feature

#201 ✨ feature: Add delete participant functionality
  schema.graphql
  src/api/abilities/entities/conferenceSupervisor.ts
  src/api/abilities/entities/delegationMember.ts
  src/api/abilities/entities/singleParticipant.ts
  src/api/resolvers/modules/user.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/services/capitalizeFirstLetter.ts
  src/routes/(authenticated)/management/[conferenceId]/participants/UserDrawer.svelte
Labels: feature

#203 ✨ feature: Add ability for management to add participants
  schema.graphql
  src/api/resolvers/modules/conferenceSupervisor.ts
  src/api/resolvers/modules/delegationMember.ts
  src/api/resolvers/modules/singleParticipant.ts
  src/api/resolvers/modules/user.ts
  src/api/services/fetchUserParticipations.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/Modal.svelte
  src/routes/(authenticated)/management/[conferenceId]/participants/UserDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/+page.gql
  src/routes/(authenticated)/management/[conferenceId]/seats/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/AddParticipantBtn.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/InitialsButton.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/SeatsTableSection.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/UserSearchModal.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/downloads/DownloadCommitteeDataBtn.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/downloads/DownloadNSADataBtn.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/downloads/DownloadSingleParticipantsDataBtn.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/downloads/DownloadSupervisorDataBtn.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/downloads/GenericDownloadButton.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/Delegations.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/NSAs.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/SingleParticipants.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/Supervisors.svelte
Labels: feature

#205 🐞 fix: Update role check for assigning supervisors and delegation members
  src/api/resolvers/modules/conferenceSupervisor.ts
  src/api/resolvers/modules/delegationMember.ts
  src/api/resolvers/modules/singleParticipant.ts
  src/api/resolvers/modules/user.ts
Labels: bug

#207 ✨ feat: add ability to assign committee seats to delegation members
  schema.graphql
  src/api/resolvers/modules/delegationMember.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/Drawer.svelte
  src/lib/components/DrawerHeader.svelte
  src/lib/components/Modal.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/Supervisor.svelte
  src/routes/(authenticated)/management/[conferenceId]/delegations/CommitteeAssignmentModal.svelte
  src/routes/(authenticated)/management/[conferenceId]/delegations/DelegationDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/individuals/IndividualDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/participants/UserDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/supervisors/SupervisorDrawer.svelte
Labels: feature

#208 ✨ feature: survey-tool on participant side
  package.json
  prisma/migrations/20250217210629_add_surveys/migration.sql
  prisma/migrations/20250218000630_add_draft_boolean_to_survey/migration.sql
  prisma/migrations/20250218123631_add_unique_constraints_to_survey_models/migration.sql
  prisma/migrations/20250218144313_drop_obsolete_enum/migration.sql
  prisma/schema.prisma
  schema.graphql
  src/api/abilities/abilities.ts
  src/api/abilities/entities/conferenceParticipantStatus.ts
  src/api/abilities/entities/surveyAnswer.ts
  src/api/abilities/entities/surveyOption.ts
  src/api/abilities/entities/surveyQuestion.ts
  src/api/resolvers/api.ts
  src/api/resolvers/builder.ts
  src/api/resolvers/modules/conference/conference.ts
  src/api/resolvers/modules/surveyAnswer.ts
  src/api/resolvers/modules/surveyOption.ts
  src/api/resolvers/modules/surveyQuestion.ts
  src/api/resolvers/modules/user.ts
  src/api/services/prismaUpsertWithRetry.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/queries/myConferenceparticipationQuery.ts
  src/routes/(authenticated)/Breadcrumbs.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/+layout.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationPreparationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/SingleParticipantPreparationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/survey/+page.gql
  src/routes/(authenticated)/dashboard/[conferenceId]/survey/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/survey/+page.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/survey/SurveyEntry.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/Delegations.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/NSAs.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/SingleParticipants.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/sections/Supervisors.svelte
Labels: feature
