Repository DeutscheModelUnitedNations/munify-delegator, pull requests merged in 2025-01, with the labels that each got.

#172 🚀 enhancement: Privacy and Language knit picks
  schema.graphql
  src/api/resolvers/modules/user.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/services/nationTranslationHelper.svelte.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/payment/delegation/+page.svelte
  src/routes/(authenticated)/my-account/+page.svelte
  src/routes/(authenticated)/my-account/form-schema.ts
Labels: enhancement

#173 ✨ feature: Add mock OAuth2 landing page and update docker-compose configuration
  dev.docker-compose.yml
  mock-oidc-landingpage.html
Labels: feature, skip-changelog

#165 🐞 fix: use more careful state management for side drawer
  bun.lockb
  package.json
  src/api/resolvers/modules/paymentTransaction.ts
  src/lib/components/Drawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/individuals/IndividualDrawer.svelte
Labels: bug

#175 ✨ Feature: Export feature for committee members
  schema.graphql
  src/api/resolvers/modules/committee.ts
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/management/[conferenceId]/seats/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/DownloadCommitteeDataBtn.svelte
Labels: feature

#174 ✨ feature: Cleanup features
  schema.graphql
  src/api/resolvers/modules/conferenceSupervisor.ts
  src/api/resolvers/modules/delegation.ts
  src/api/resolvers/modules/delegationMember.ts
  src/api/resolvers/modules/singleParticipant.ts
  src/i18n/de.json
  src/i18n/en.json
  src/routes/(authenticated)/Breadcrumbs.svelte
  src/routes/(authenticated)/management/[conferenceId]/+layout.svelte
  src/routes/(authenticated)/management/[conferenceId]/cleanup/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/cleanup/Modal.svelte
  src/routes/(authenticated)/management/[conferenceId]/cleanup/Section.svelte
  src/routes/(authenticated)/management/[conferenceId]/cleanup/types.ts
Labels: feature

#179 ⬆️ improvement: Allow Supervisors to track payment and postal status of their students
  add_new_translation.ts
  bun.lockb
  package.json
  src/api/resolvers/builder.ts
  src/api/resolvers/modules/delegation.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/DelegationStatusTable/Entry.svelte
  src/lib/components/DelegationStatusTable/Wrapper.svelte
  src/lib/queries/myConferenceparticipationQuery.ts
  src/lib/services/formatNames.ts
  src/lib/services/getSimplifiedPostalStatus.ts
  src/routes/(authenticated)/dashboard/[conferenceId]/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/committeeAssignment/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/payment/+page.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/payment/ReferenceMaker.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationPreparationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/DelegationRegistrationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/SingleParticipantPreparationStage.svelte
  src/routes/(authenticated)/dashboard/[conferenceId]/stages/Supervisor.svelte
  src/routes/(authenticated)/management/[conferenceId]/cleanup/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/participants/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/payments/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/plausibility/PlausibilityDetails.svelte
  src/routes/(authenticated)/management/[conferenceId]/seats/+page.svelte
  src/routes/assignment-assistant/[projectId]/DelegationCard.svelte
  src/routes/assignment-assistant/[projectId]/Sighting.svelte
  src/routes/assignment-assistant/[projectId]/SingleParticipantCard.svelte
  src/routes/assignment-assistant/[projectId]/Summary.svelte
  src/tasks/mailSync.ts
Labels: enhancement

#182 🚀 enhancement: Trim search value input on payments page
  src/routes/(authenticated)/management/[conferenceId]/payments/+page.svelte
Labels: enhancement

#183 ⬆️ improvement: bring back No-Conference Screen on Dashboard
  src/routes/(authenticated)/dashboard/+page.svelte
Labels: enhancement

#178 ✨ feature: add stats about the diet and gender distribution in signups
  prisma/migrations/20250115152503_/migration.sql
  prisma/schema.prisma
  schema.graphql
  src/api/abilities/entities/conferenceSupervisor.ts
  src/api/resolvers/modules/conference/statistics.ts
  src/api/resolvers/modules/user.ts
  src/api/services/stats.ts
  src/i18n/de.json
  src/i18n/en.json
  src/lib/components/CountryStats/CountryStats.svelte
  src/lib/components/CountryStats/SingleStatFromWB.svelte
  src/lib/components/Dashboard/TodoTable.svelte
  src/routes/(authenticated)/dashboard/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/participants/UserDrawer.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/+page.ts
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/AgeChart.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/AppliedChartAndStats.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/DietMatrix.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/DistributionChart.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/Filter.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/GenderMatrix.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/NumberMatrix.svelte
  src/routes/(authenticated)/my-account/+page.svelte
  src/routes/(authenticated)/my-account/form-schema.ts
  src/routes/(authenticated)/registration/[conferenceId]/create-delegation/+page.svelte
  tailwind.config.ts
Labels: feature

#181 ✨ feature: Add postal and payment stats
  .github/workflows/build_run.yml
  bun.lockb
  schema.graphql
  src/api/resolvers/modules/conference/statistics.ts
  src/api/services/stats.ts
  src/routes/(authenticated)/management/[conferenceId]/stats/+page.svelte
  src/routes/(authenticated)/management/[conferenceId]/stats/+page.ts
  src/routes/(authenticated)/management/[conferenceId]/stats/stats.svelte.ts
  src/routes/(authenticated)/management/[conferenceId]/stats/widgets/Status.svelte
Labels: feature

#184 🐞 fix: enable single transactions for delegates again
  src/routes/(authenticated)/dashboard/[conferenceId]/payment/+page.svelte
Labels: bug
